package tqs.ua.pt;

// Generated by Selenium IDE
// import org.junit.Test;
// import org.junit.Before;
// import org.junit.After;
// import static org.junit.Assert.*;
// import static org.hamcrest.CoreMatchers.is;
// import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.extension.ExtendWith;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(SeleniumJupiter.class)
public class AlternativaTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @FindBy(xpath = "//option[. = 'Mexico City']")
  private WebElement mexicoCity;

  @FindBy(xpath = "//option[. = 'Rome']")
  private WebElement rome;

  @FindBy(css = ".btn-primary")
  private WebElement btnPrimary1;

  @FindBy(css = "tr:nth-child(4) .btn")
  private WebElement planeOption;

  @FindBy(id = "inputName")
  private WebElement inputName;

  @FindBy(id = "address")
  private WebElement address;

  @FindBy(id = "city")
  private WebElement city;

  @FindBy(id = "state")
  private WebElement state;

  @FindBy(id = "zipCode")
  private WebElement zipCode;

  @FindBy(xpath = "//option[. = 'American Express']")
  private WebElement americanExpress;

  @FindBy(id = "creditCardNumber")
  private WebElement creditCardNumber;

  @FindBy(id = "creditCardMonth")
  private WebElement creditCardMonth;

  @FindBy(id = "creditCardYear")
  private WebElement creditCardYear;

  @FindBy(id = "nameOnCard")
  private WebElement nameOnCard;

  @FindBy(css = ".checkbox")
  private WebElement checkbox;

  @FindBy(css = ".btn-primary")
  private WebElement btnPrimary2;


  @Test
  public void alternativa() {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1920, 983));

    PageFactory.initElements(driver, this);

    mexicoCity.click();
    rome.click();
    btnPrimary1.click();
    planeOption.click();
    inputName.sendKeys("Oscar Nunez");
    address.sendKeys("Calle San Francisco");
    city.sendKeys("Cancun");
    state.sendKeys("Cancun");
    zipCode.sendKeys("999");
    americanExpress.click();
    creditCardNumber.sendKeys("666");
    creditCardMonth.sendKeys("03");
    creditCardYear.sendKeys("2021");
    nameOnCard.sendKeys("Oscar Nunez");
    checkbox.click();
    btnPrimary2.click();
    assertThat(driver.getTitle()).isEqualTo("BlazeDemo Confirmation");
  }
}
